### ISSUE TITLE
Stub application doesn't have stderr when running without console.

### ISSUE THREAD

**Issue by gerasimovich-a** [beeware/briefcase-windows-VisualStudio-template#17]
### Describe the bug

I'm trying to deploy my ML model with briefcase. It works with `briefcase run` but i have an error when launch an .exe

`CatBoostError: Expected callable object or stream-like object`
`\windows\app\src\app_packages\catboost\core.py", line 120, in _get_stream_like_object`

https://github.com/catboost/catboost/blob/master/catboost/python-package/catboost/core.py

i found out that `sys.stderr` is `None` in case of running exe file

How can i fix it? I really appreciate any help you can provide

### Expected behavior

sys.stderr is not None

### Environment

- Operating System: Windows
- Python version: 3.9.13
- Software versions:
  - Briefcase:

**Comment by rmartin16** [comment]
Mild [defense](https://docs.python.org/3/library/sys.html#sys.__stderr__) for catboost implementing a change.

> Note Under some conditions stdin, stdout and stderr as well as the original values __stdin__, __stdout__ and __stderr__ can be None. It is usually the case for Windows GUI apps that aren’t connected to a console and Python apps started with pythonw.

**Comment by freakboy3742** [comment]
🤦  I was looking for a Unix stdout/err reference, and forgot that Python's docs might have something to say on the matter.

I'd call that a little more than "mild"... that's pretty much canonical defence of what the stub app is doing, IMHO :-) 

On the basis that Briefcase has a documented defence of it's implementation, and workarounds exist, I'm going to close this issue and call it a bug in catboost.
