### ISSUE TITLE
make the release folder more clearly

### ISSUE THREAD

**Issue by Jzhenli** [beeware/briefcase-windows-VisualStudio-template#30]
### What is the problem or limitation you are having?

@freakboy3742 Hi, when we build win app, it will put the python runtime files into the root folder, and it looks messy, would u consider to make the template as follows,
<img width="338" alt="1715737087341" src="https://github.com/beeware/briefcase-windows-VisualStudio-template/assets/42105688/3740b190-bd87-41a0-8d1e-2c74712adc94">

### Describe the solution you'd like

change the template as above

### Describe alternatives you've considered

change the template as above

**Comment by freakboy3742** [comment]
Thanks for the suggestion; however, this ultimately isn't possible, as Windows doesn't provide a mechanism for customizing the dynamic linking path - it requires that the DLLs are in the same folder as the stub binary. I agree this is messy; however, we are limited by the constraint of the platform itself.
